// src/mallData.js

export const categories = [
  "All",
  "Fashion",
  "Food & Beverage",
  "Electronics",
  "Beauty",
  "Kids",
  "Entertainment",
  "Services",
  "Supermarket",
];

export const mallFloors = [
  {
    id: "L1",
    name: "Level 1",
    gridSize: 10, // 10x10 условная сетка
    description: "Main entrance, supermarket, electronics, services",
    shops: [
      {
        id: "zara-l1",
        name: "ZARA",
        category: "Fashion",
        x: 2,
        y: 2,
        zone: "Fashion Gallery",
        isAnchor: true,
      },
      {
        id: "hm-l1",
        name: "H&M",
        category: "Fashion",
        x: 3,
        y: 2,
        zone: "Fashion Gallery",
      },
      {
        id: "starbucks-l1",
        name: "Starbucks",
        category: "Food & Beverage",
        x: 1,
        y: 5,
        zone: "Central Atrium",
      },
      {
        id: "burgerking-l1",
        name: "Burger King",
        category: "Food & Beverage",
        x: 2,
        y: 5,
        zone: "Food Court",
      },
      {
        id: "apple-l1",
        name: "Apple Store",
        category: "Electronics",
        x: 7,
        y: 3,
        zone: "Tech Zone",
        isAnchor: true,
      },
      {
        id: "xiaomi-l1",
        name: "Xiaomi Store",
        category: "Electronics",
        x: 8,
        y: 3,
        zone: "Tech Zone",
      },
      {
        id: "carefour-l1",
        name: "Carrefour",
        category: "Supermarket",
        x: 6,
        y: 7,
        zone: "Hypermarket",
        isAnchor: true,
      },
      {
        id: "bank-l1",
        name: "Halyk Bank",
        category: "Services",
        x: 4,
        y: 7,
        zone: "Service Alley",
      },
      {
        id: "pharmacy-l1",
        name: "Pharmacy 24/7",
        category: "Services",
        x: 5,
        y: 5,
        zone: "Central Atrium",
      },
      {
        id: "kidsstore-l1",
        name: "Mothercare",
        category: "Kids",
        x: 3,
        y: 7,
        zone: "Kids World",
      },
      {
        id: "info-l1",
        name: "Information Desk",
        category: "Services",
        x: 5,
        y: 2,
        zone: "Main Entrance",
        isAnchor: true,
      },
      {
        id: "escalator-l1",
        name: "Escalator to Level 2",
        category: "Services",
        x: 5,
        y: 4,
        zone: "Central Atrium",
        isConnector: true,
      },
    ],
  },
  {
    id: "L2",
    name: "Level 2",
    gridSize: 10,
    description: "Fashion, beauty, entertainment",
    shops: [
      {
        id: "zara-l2",
        name: "ZARA Woman",
        category: "Fashion",
        x: 2,
        y: 2,
        zone: "Fashion Boulevard",
        isAnchor: true,
      },
      {
        id: "bershka-l2",
        name: "Bershka",
        category: "Fashion",
        x: 3,
        y: 2,
        zone: "Fashion Boulevard",
      },
      {
        id: "sephora-l2",
        name: "Sephora",
        category: "Beauty",
        x: 7,
        y: 3,
        zone: "Beauty Street",
      },
      {
        id: "inglot-l2",
        name: "Inglot",
        category: "Beauty",
        x: 8,
        y: 3,
        zone: "Beauty Street",
      },
      {
        id: "lego-l2",
        name: "LEGO Store",
        category: "Kids",
        x: 3,
        y: 6,
        zone: "Kids World",
      },
      {
        id: "cinema-l2",
        name: "Cinemax",
        category: "Entertainment",
        x: 7,
        y: 7,
        zone: "Cinema & Fun",
        isAnchor: true,
      },
      {
        id: "foodcourt-l2",
        name: "Food Court",
        category: "Food & Beverage",
        x: 5,
        y: 6,
        zone: "Food Terrace",
      },
      {
        id: "playground-l2",
        name: "Kids Playground",
        category: "Entertainment",
        x: 2,
        y: 7,
        zone: "Kids World",
      },
      {
        id: "salon-l2",
        name: "Beauty Salon",
        category: "Beauty",
        x: 6,
        y: 5,
        zone: "Beauty Street",
      },
      {
        id: "escalator-l2",
        name: "Escalator to Level 1",
        category: "Services",
        x: 5,
        y: 4,
        zone: "Central Atrium",
        isConnector: true,
      },
    ],
  },
];

export const allShops = mallFloors.flatMap((floor) =>
  floor.shops.map((shop) => ({
    ...shop,
    floorId: floor.id,
    floorName: floor.name,
  }))
);
